#+TITLE:  8th Quiz
#+AUTHOR: Rick Neff
#+EMAIL:  rick.neff@gmail.com
#+LANGUAGE:  en
#+OPTIONS:   H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+STARTUP:   showeverything

This is a quiz on Bayes' Theorem and its generalized version.

* 1st Question

  Automating the process of finding bugs in source code requires the
  use of heuristics, or pattern-matching on the code. There is no deep
  understanding of the code involved, hence such a tool cannot be
  perfect at detecting bugs. A certain bug-detection tool is correct
  80% of the time and incorrect the rest of the time. This means that
  on average out of every 100 bugs, the tool will detect 80 of them,
  and fail to detect 20 of them. Also, out of 100 non-bugs, the tool
  will report 20 bugs and 80 non-bugs, on average. The tool is run on
  source code that is 10% buggy. That is, one line out of every ten
  contains a bug. Given that the tool detects a bug in some line of
  code, what is the probability that this line of code actually
  contains a bug? 

** Answer
30%
*** Feedback

* 2nd Question

  Using the information in the 1st Question, calculate to
  two-decimal-digit precision the values that go at the leaves of the
  binary tree shown below, where the arrow pointing to the topmost:
  leaf is labeled to show what goes there. Hint: The four leaves
  correspond to the four quadrants of trutH versus tesT.

:
:            /.08<---------------------- p(H) * p(T | H) goes here
:           / p(T | H)
:          /          
:         /\          
:        /  \ p(!T | H)
:  p(H) /    \.02       
:      /       
:     /         
:     \        
:      \       
: p(!H) \    /.18 
:        \  / p(T | !H)
:         \/           
:          \           
:           \ p(!T | !H) 
:            \ .16
:              

* 3rd Question

  Suppose that a Bayesian spam filter is trained on a set of 500 spam
  messages and 200 messages that are not spam. The word /exciting/
  appears in 40 spam messages and in 25 messages that are not
  spam. Would an incoming message be rejected as spam if it contains
  the word /exciting/ and the threshold for rejecting spam is 0.9?

  The procedure to follow is to compute from the training set data and
  a message containing a given word the value /p/, the probability of
  a message being spam, the value /q/, the probability of a message
  *not* being spam, the value /r/, the ratio of /p/ to the sum of /p/
  and /q/, and finally, to compare the value /r/ to the threshold to
  decide whether or not an incoming message with a given word would be
  rejected.

** Answer

*** Feedback

* 4th Question

  Suppose that we have prior information concerning whether a random
  incoming message is spam.  In particular, suppose that over a time
  period, we find that /s/ spam messages arrive and /h/ messages
  arrive that are not spam.

  Use this information to estimate /p(S)/, the probability that an
  incoming message is spam, and \(p(\overline{S})\), the probability an
  incoming message is not spam. Express these probabilities in terms
  of /s/ and /h/.

** Answer

*** Feedback

* 5th Question

  Use Bayes' Theorem and the probabilities you computed in the
  previous question to estimate the probability than an incoming
  message containing the word /w/ is spam, where /p(w)/ is the
  probability that /w/ occurs in a spam message and /q(w)/ is the
  probability that /w/ occurs in a message that is not spam.

** Answer

*** Feedback

* 6th Question

  There are three sheets of paper in a folder. One sheet has writing
  on both sides, one has writing on one side and is blank on the other
  side, and the third sheet of paper is blank on both sides. Without
  looking you randomly pull one sheet of paper out of the folder and
  see that it is blank on the side you're looking at. What is the
  probability that the other side is blank as well?

** Answer

*** Feedback

* 7th Question

  Three different vegetables, turnips, eggplant and asparagus, make
  Bill sick sometimes. There is a 50% chance he will be sick if he
  eats turnips. If he eats eggplant, there is a 20% chance he will be
  sick. The probability that he will be sick when he eats asparagus is
  only 5%.

  Bill gets sick after dinner where he ate one of those three
  vegetables. What is the probability that he ate turnips?

  (Assume that for each of the three vegetables, there is a 1/3 chance
  he ate it.)

** Answer

*** Feedback

* 8th Question

  Change the prior probabilities of Bill eating these vegetables to a
  30% chance he ate turnips, a 10% chance he ate eggplant, and a 60%
  chance he ate asparagus?

  Now what is the probability that Bill ate turnips, given that he got
  sick?

** Answer

*** Feedback


